### PR TITLE
PTZ research

### PR DESCRIPTION
**Pull request by Phaeilo**
Added some information about interfacing with the PTZ driver.

### CODE REVIEW

**Comment by happytm** [comment]
Is this SOC capable of monitor mode ?

**Comment by Phaeilo** [comment]
Are you referring to the wireless interface?

**Comment by ant-thomas** [comment]
Fantastic work. Merging now.
I'm going to do a relatively large update, possibly this weekend, and I'll now be including your PTZ work.

**Comment by ant-thomas** [comment]
@Phaeilo Are you able to provide the binary?

**Comment by happytm** [comment]
Yes. I wanted to use this  camera on a drone.

**Pull request merged**
