### PR TITLE
Source and binaries to set p2pcam params and set audio volume

### PR DESCRIPTION
**Pull request by deorder**
See commits

### CODE REVIEW

**Comment by ant-thomas** [comment]
The goke volume program is fantastic. I assumed it was a noisy regulator but setting volume to 0 quietens the camera massively.

**Comment by djwillis** [comment]
Can I ask what license this code is under?

**Comment by deorder** [comment]
For me MIT or even public domain is fine.

**Comment by deorder** [comment]
For me MIT or even public domain is fine.

**Comment by djwillis** [comment]
Thanks, wanted to check that it was not derived from any of the closed source Goke stuff :). Great bit of work.

**Comment by ant-thomas** [comment]
Do either of you have any idea how to potentially control the PTZ from the command line or via a program?
```
ai_dev
ao_dev
gk_fw
gk_log
gk_video
ptz
```
I'm guessing it is via ```/dev/ptz```

**Comment by deorder** [comment]
@djwillis  Thanks. More to come. Among this a "sandbox" that prevents "p2pcm" from running / calling certain commands / syscalls.

@ant-thomas Will look into it if I have time (not much this week). Should be very easy to find out using my ioctl debug tool and using "strace" while performing the action:

[strace.tar.gz](https://github.com/ant-thomas/zsgx1hacks/files/1484625/strace.tar.gz)

I think it uses PWM to drive the motor.

**Comment by ant-thomas** [comment]
@deorder @djwillis Have either of you managed to get an active WiFi connection on a camera that has never been setup by the app?

I've tried various ways
Copying a config file with correct creds to ```/home/wpa_supplicant.conf```
Using @deorder ```goke_p2pcam_param``` program to update ```/home/devParam.dat``` - the update happens but there's no WiFi connection created, even after reboot.

Also manually tried running ```wpa_supplicant``` pointing to my conf file but that fails.
I get the feeling that the camera/p2pcam needs to think it is "configured". There's certainly plenty of files that get updated on an app activated camera.

**Comment by deorder** [comment]
@ant-thomas I noticed that as well. After a while p2pcam starts an "ap scan" which results in any available wifi connection to get disconnected. So you can move the bullet point to TODO again. I have to disassemble the binary to see what is happening. It is possible there is a checksum test somewhere.

**Comment by sanscorp1** [comment]
I alao noticed that the cam keeps rebooting when there is no internet connection (blocked in router)

**Comment by deorder** [comment]
@sanscorp1 It does not reboot if correctly configured through the official app first. After this it works even without an internet connection.

**Comment by sanscorp1** [comment]
The cam is configured and works. It went offline after configuring, still works via qnap surveillance station (onvif) but keeps rebooting.

Do you think it's possible to reconfigure the complete camera to work with an embedded web page?
Maybe even via the tenvis app?

I still have to gain access to the tenvis cam (old model, 640x480).

**Comment by deorder** [comment]
@sanscorp1

The reason it reboots is because the watchdog gets triggered after it is initialized by "p2pcam". It is also configured to automatically reboot once in a while. I am currently reverse engineering "p2pcam" and already got the audio output to work. This is a very time consuming task because everything has to be initialized the right way, requiring several calls to ioctl, opening and mmapping the devices. I am looking into using Motion to replace "p2pcam". It has a simple HTTP interface.

**Comment by sanscorp1** [comment]
I havn't had the time yet, tried to find the uart on the tenvis cam but no luck. There's also 5v between tx/gnd and rx/gnd that makes me doubt the interface is good. The camera starts booting when I attach the interface.

I look forward to the end result and will be happy to test anything. But again: I have no experience at all.

**Pull request merged**
